import React, { useEffect, useState } from 'react';
import { dataService } from '../services/dataService';
import { ArrowUpRight, Database, FileText, Layers } from 'lucide-react';

const Dashboard: React.FC = () => {
  const [stats, setStats] = useState({
    products: 0,
    generated: 0,
    potential: 0
  });

  useEffect(() => {
    const products = dataService.getProducts();
    const comparisons = dataService.getComparisons();
    const potential = dataService.getPotentialCombinationsCount();

    setStats({
      products: products.length,
      generated: comparisons.length,
      potential: potential
    });
  }, []);

  const StatCard = ({ title, value, sub, icon: Icon, color }: any) => (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 flex items-start justify-between hover:shadow-md transition-shadow">
      <div>
        <p className="text-slate-500 text-sm font-medium mb-1">{title}</p>
        <h3 className="text-3xl font-bold text-slate-800">{value}</h3>
        <p className="text-xs text-slate-400 mt-2">{sub}</p>
      </div>
      <div className={`p-3 rounded-lg ${color}`}>
        <Icon className="text-white" size={24} />
      </div>
    </div>
  );

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-2xl font-bold text-slate-800">Dashboard Overview</h2>
        <p className="text-slate-500">Welcome back, P'Ook. Here is your SEO factory status.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <StatCard 
          title="Total Products" 
          value={stats.products} 
          sub="Items in Supabase"
          icon={Database} 
          color="bg-blue-500"
        />
        <StatCard 
          title="Potential Pages (pSEO)" 
          value={stats.potential} 
          sub="Combinations (N * (N-1) / 2)"
          icon={Layers} 
          color="bg-purple-500"
        />
        <StatCard 
          title="Generated Pages" 
          value={stats.generated} 
          sub="Indexed Content"
          icon={FileText} 
          color="bg-green-500"
        />
      </div>

      <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
        <h3 className="text-lg font-bold text-slate-800 mb-4">Quick Actions</h3>
        <div className="flex gap-4">
           {/* J's Note: Mock action to simulate adding content quickly */}
           <button className="flex items-center px-4 py-2 bg-slate-100 text-slate-700 rounded-lg hover:bg-slate-200 text-sm font-medium">
             Add New Product
           </button>
           <button className="flex items-center px-4 py-2 bg-blue-50 text-blue-700 rounded-lg hover:bg-blue-100 text-sm font-medium">
             Run Batch Generator
             <ArrowUpRight size={16} className="ml-2" />
           </button>
        </div>
      </div>

      <div className="bg-indigo-900 text-white p-6 rounded-xl shadow-lg relative overflow-hidden">
        <div className="relative z-10">
          <h3 className="text-xl font-bold mb-2">Programmatic SEO Tip</h3>
          <p className="text-indigo-200 max-w-2xl">
            "Google hates empty tables. Make sure your 'User Opinion' section generated by Gemini is comprehensive. 
            We are aiming for Long-tail keywords like 'Is iPhone 16 better than S24 for gaming?'"
          </p>
        </div>
        <div className="absolute right-0 bottom-0 opacity-10 transform translate-x-10 translate-y-10">
           <Layers size={200} />
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
